name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ziyahulhaq/employs:latest

      - name: Delete Old docker container
        run: sudo docker rm -f employs-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3444:3444 --name employs-container ziyahulhaq/employs:latest
