name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install server Dependencies
        run: |
          cd server
          npm install

      - name: Install frdend Dependencies
        run: |
          cd frdend
          npm install

      - name: Build React App
        run: |
          cd frdend
          npm run build

      - name: Run Backend Tests
        run: |
          cd server
          npm test
