name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            server/package-lock.json
            frdend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: server
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: frdend
        run: npm install

      - name: Build Frontend
        working-directory: frdend
        run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Publish
        run: echo "Build completed successfully"

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ziyahulhaq/employs
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
