name: Node.js CI

on:
  push:
    branches: ["main"]
 

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  dependency-submission:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
